disable_functions = exec,system
cgi.fix_pathinfo=0
max_execution_time = 60
max_input_time = 60
memory_limit=256M

upload_max_filesize = 65M
post_max_size = 65M
max_file_uploads = 5

# local
display_errors = off
register_globals = off
display_startup_errors = off
expose_php = off

; maximum memory allocated to store the results
realpath_cache_size=4096K

; save the results for 10 minutes (600 seconds)
realpath_cache_ttl=600
