services:
    ast-nginx:
        image: nginx:latest
        container_name: ast-nginx
        volumes:
            - ./:/var/www
            - ./_docker/prod/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "8077:80"
        networks:
            - ast-network
        depends_on:
            - ast-app
            - ast-db
        restart: always

    ast-app:
        build:
            context: .
            dockerfile: _docker/prod/Dockerfile
        container_name: ast-app
        networks:
            - ast-network
        volumes:
            - ./:/var/www
        env_file:
            - ./../secrets/.env.prod
        restart: always

    ast-db:
        image: postgres:18.3-bookworm
        container_name: ast-db
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        env_file:
            - ./../secrets/.env.prod
        ports:
            - "5486:5432"
        volumes:
            - /var/lib/ast-php-pg18:/var/lib/postgresql:rw
            - ./_docker/prod/postgres/custom-postgresql.conf:/etc/postgresql/postgresql.conf
        command: postgres -c config_file=/etc/postgresql/postgresql.conf
        networks:
            - ast-network
        restart: always

networks:
    ast-network:
        driver: bridge
