services:
    ast-nginx:
        image: nginx:latest
        container_name: ast-nginx
        volumes:
            - ./:/var/www
            - ./_docker/dev/fpm/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "8083:80"
        networks:
            - ast-network
        depends_on:
            - ast-app

    ast-app:
        build:
            context: .
            dockerfile: _docker/dev/fpm/Dockerfile
        container_name: ast-app
        volumes:
            - ./:/var/www
        networks:
            - ast-network

    ast-db:
        image: postgres:18.3-bookworm
        container_name: ast-db
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        env_file:
            - .env
        ports:
            - "5487:5432"
        volumes:
            - /var/lib/ast-php-pg18:/var/lib/postgresql:rw
            - ./_docker/dev/postgres/custom-postgresql.conf:/etc/postgresql/postgresql.conf
        command: postgres -c config_file=/etc/postgresql/postgresql.conf
        networks:
            - ast-network

networks:
    ast-network:
        driver: bridge
