# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    rateLimiter.allowance: '%env(RATE_LIMITER_ALLOWANCE_REQUESTS)%'
    rateLimiter.durationSeconds: '%env(RATE_LIMITER_TIME_DURATION_SECONDS)%'

    app.blockingParanoia: '%env(BLOCKING_PARANOIA)%'
    app.defaultUri: '%env(DEFAULT_URI)%'
    app.registerNewUserViaApi: '%env(REGISTERING_NEW_USERS_VIA_API)%'

    file.useFileEncryption: '%env(FILE_USE_ENCRYPTION)%'
    file.encryptionKey: '%env(FILE_ENCRYPTION_KEY)%'
    file.storage: '%env(FILE_STORAGE)%'

    noteFile.uploadMaxSize: '%env(NOTE_FILE_UPLOAD_MAX_SIZE)%'
    noteFile.limitStoragePerUser: '%env(NOTE_FILE_LIMIT_STORAGE_PER_USER)%'
    noteFile.savePath: '%env(NOTE_FILE_SAVE_PATH)%'

    drive.savePath: '%env(DRIVE_FILE_SAVE_PATH)%'
    drive.limitStoragePerUser: '%env(DRIVE_LIMIT_STORAGE_PER_USER)%'
    drive.uploadMaxSize: '%env(DRIVE_UPLOAD_MAX_SIZE)%'

    s3.endpoint: '%env(S3_ENDPOINT)%'
    s3.accessKey: '%env(S3_ACCESS_KEY)%'
    s3.secretAccessKey: '%env(S3_SECRET_ACCESS_KEY)%'
    s3.useSSL: '%env(S3_USE_SSL)%'
    s3.bucketName: '%env(S3_BUCKET_NAME)%'
    s3.location: '%env(S3_LOCATION)%'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Layer/Domain/Entity/'
            - '../src/Kernel.php'
            - '../src/Exception/ExceptionNormalizer.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\EventListener\LocaleListener:
        arguments:
            $defaultLocale: '%kernel.default_locale%'
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 20 }

    App\EventListener\LangListener:
        arguments:
            $symfonyTranslator: '@translator'
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 19 }

    App\EventListener\ValidationExceptionListener:
        arguments:
            $isDebug: '%kernel.debug%'
        tags:
            - { name: kernel.event_listener, event: kernel.exception, priority: 18 }

    App\EventListener\BlockIPListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 17 }

    App\EventListener\RateLimiterListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 16 }

    App\EventListener\RateLimiterResponseListener:
        tags:
            - { name: kernel.event_listener, event: kernel.response, priority: 15 }
